[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
allow_paths = ["../node_modules", "../../node_modules"]

[rpc_endpoints]
celo-alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"

[etherscan]
celo-alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api"}
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api"}